### PR TITLE
With the official private networks ranges

### PR DESCRIPTION
**Pull request by jmcabrera**
From [wikipedia](https://en.wikipedia.org/wiki/Private_network), using the full ranges for private networks.
These new ranges include the previously set ones.

### CODE REVIEW

**Comment by jmcabrera** [comment]
after-thought: I did not look into how redsocks deals with ipv6...

**Comment by ncarlier** [comment]
Good point buddy.
But I am not confident that is a good idea to remove the 127.0.0.0 line. If you do so I think that a request inside the container on its localhost interface will be redirected through redsocks.  This kind of request can be useful for a health check command. Can you check this ?

**Comment by jmcabrera** [comment]
It will indeed... And it was not my intention, this range should remain UNproxified imho, reverting back this line :)

**Comment by ncarlier** [comment]
Thanks!

**Pull request merged**
